import { FreightRow, FreightAnalytics } from '@/types/freightData';

// Freight Data
export const freightData: FreightRow[] = [
    {
    id: 1,
    reference: 'SR_24-001_NBO hub_Zimbabwe',
    description: 'Cholera kits and Tents',
    destination: 'Zimbabwe',
    kenyaAirways: 18681.0,
    kuehneNagel: 18681,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 7352.98,
    volume: 24.68,
    awardedTo: 'Kenya Airways via Kuehne Nagel',
    arrivalDate: '17-Jan-24',
    shippingMode: 'Air'
  },
  {
    id: 2,
    reference: 'SR_24-002_NBO hub_Zambia_(SR_23-144)',
    description: 'Cholera kitsORSBody bagsMasks and Glucometers',
    destination: 'Zambia',
    kenyaAirways: 59500.0,
    kuehneNagel: 59500,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 29972,
    weight: 14397.0,
    volume: 50.88,
    awardedTo: 'Kenya Airways via Kuehne Nagel',
    arrivalDate: '01-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 3,
    reference: 'SR_24-004_NBO hub_Zambia',
    description: 'Tents GlovesPPEs and Drugs ',
    destination: 'Zambia',
    kenyaAirways: 0.0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 10168.0,
    volume: 59.02,
    awardedTo: 'KQ:Direct charter',
    arrivalDate: '02-Jun-24',
    shippingMode: 'Air'
  },
  {
    id: 4,
    reference: 'SR_24-005A_NBO hub_Zimbabwe',
    description: 'Cholera kits TentsBody bags and Gowns',
    destination: 'Zimbabwe',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 9087.24,
    volume: 44.97,
    awardedTo: 'KQ:Direct charter',
    arrivalDate: '02-Jun-24',
    shippingMode: 'Air'
  },
  {
    id: 5,
    reference: 'SR_24-005_NBO hub_Zimbabwe',
    description: 'Cholera kits TentsBody bags and Gowns',
    destination: 'Zimbabwe',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 30.0,
    volume: 0.25,
    awardedTo: 'KQ:Direct charter',
    arrivalDate: '02-Jun-24',
    shippingMode: 'Air'
  },
  {
    id: 6,
    reference: ' SR_24-005B_NBO hub_Zimbabwe',
    description: 'Cholera kits and Tents',
    destination: 'Zimbabwe',
    kenyaAirways: 8694.0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 8694,
    weight: 3506.0,
    volume: 12.17,
    awardedTo: 'Kenya Airways via Kuehne Nagel',
    arrivalDate: '02-May-24',
    shippingMode: 'Air'
  },
  {
    id: 7,
    reference: 'SR_24-008_NBO hub_Madagascar',
    description: 'Laboratory Items',
    destination: 'Madagascar',
    kenyaAirways: 1029.0,
    kuehneNagel: 466,
    scanGlobal: 1029,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 574,
    weight: 179.33,
    volume: 2.71,
    awardedTo: 'Kenya Airways via Kuehne Nagel',
    arrivalDate: '02-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 8,
    reference: ' SR_24-011_NBO hub_Comoros',
    description: 'Laboratory itemsKit Cholera and Sprayers',
    destination: 'Comoros',
    kenyaAirways: 781.0,
    kuehneNagel: 679,
    scanGlobal: 781,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 521,
    weight: 1289.0,
    volume: 5.93,
    awardedTo: 'Kenya Airways via Freight in Time',
    arrivalDate: '16-Feb-24',
    shippingMode: 'Air'
  },
  {
    id: 9,
    reference: 'SR_24-012_NBO hub_South Sudan',
    description: 'KIT MAJOR TRAUMA backpack',
    destination: 'South Sudan',
    kenyaAirways: 668.0,
    kuehneNagel: 248,
    scanGlobal: 668,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 261,
    weight: 126.0,
    volume: 0.57,
    awardedTo: 'Kenya Airways',
    arrivalDate: '20-Feb-24',
    shippingMode: 'Air'
  },
  {
    id: 10,
    reference: 'SR_24-016_NBO hub_Mayotte',
    description: 'Cholera RDTs',
    destination: 'Mayotte',
    kenyaAirways: 0,
    kuehneNagel: 323,
    scanGlobal: 511,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 527,
    weight: 16.9,
    volume: 0.17,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '27-Feb-24',
    shippingMode: 'Air'
  },
  {
    id: 11,
    reference: 'SR_24-017_NBI hub_Mauritius',
    description: 'Mosquito Nets Repellant and Masks',
    destination: 'Mauritius',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 10867,
    weight: 3377.04,
    volume: 12.73,
    awardedTo: 'Freight In Time',
    arrivalDate: '03-Jan-24',
    shippingMode: 'Air'
  },
  {
    id: 12,
    reference: 'SR_24-014_NBO hub_Ethiopia',
    description: '(IEHK 2017 SUPPLEMENTARY) MODULE MALARIA',
    destination: 'Ethiopia',
    kenyaAirways: 0,
    kuehneNagel: 14853,
    scanGlobal: 15098,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 12148,
    weight: 3365.0,
    volume: 17.35,
    awardedTo: 'Freight In Time',
    arrivalDate: '16-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 13,
    reference: 'SR_24-020_NBO hub_Congo Brazzaville',
    description: 'RDT Covid 19 Kits',
    destination: 'Congo Brazzaville',
    kenyaAirways: 0,
    kuehneNagel: 573,
    scanGlobal: 586,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 633,
    weight: 178.0,
    volume: 0.23,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '16-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 14,
    reference: 'SR_24-018_NBO hub_Malawi',
    description: 'TMDs',
    destination: 'Malawi',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 50,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 0.04,
    volume: 0.0,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '03-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 15,
    reference: 'SR_24-024_NBO hub_Burundi',
    description: 'IEHK Kits and Tents',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 4828,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 3616,
    weight: 1561.75,
    volume: 6.61,
    awardedTo: 'Freight In Time',
    arrivalDate: '23-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 16,
    reference: 'SR_24-021_NBO hub_Mauritius',
    description: 'Mosquito Repellant and Masks',
    destination: 'Mauritius',
    kenyaAirways: 10867.0,
    kuehneNagel: 7512,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 10867,
    weight: 2886.0,
    volume: 7.64,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '17-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 17,
    reference: 'SR_24-025_NBO hub_Senegal Hub',
    description: 'TMDs & Radio Motorola',
    destination: 'Senegal',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 1257,
    weight: 17.92,
    volume: 0.09,
    awardedTo: 'Freight In Time',
    arrivalDate: '22-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 18,
    reference: 'SR_24-030_NBO hub_Congo Kinshasa',
    description: 'RDT COVID-19 Kits ',
    destination: 'Congo Kinshasa',
    kenyaAirways: 0,
    kuehneNagel: 1452,
    scanGlobal: 2324,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 2004,
    weight: 388.0,
    volume: 2.93,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '19-Apr-24',
    shippingMode: 'Air'
  },
  {
    id: 19,
    reference: 'SR_24-031_NBO hub_Zimbabwe',
    description: 'Boots Cholera kitsBody bags and Sprayers',
    destination: 'Zimbabwe',
    kenyaAirways: 6775.0,
    kuehneNagel: 6395,
    scanGlobal: 6775,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 5615,
    weight: 1448.73,
    volume: 10.2,
    awardedTo: 'Freight In Time',
    arrivalDate: '26-Apr-24',
    shippingMode: 'Air'
  },
  {
    id: 20,
    reference: 'SR_24-027_NBO hub_Zambia',
    description: 'Cholera kits IEHK Kits and Tents',
    destination: 'Zambia',
    kenyaAirways: 33498.0,
    kuehneNagel: 30803,
    scanGlobal: 27965,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 33498,
    weight: 10113.91,
    volume: 40.67,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '05-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 21,
    reference: 'SR_24-029_NBO hub_Madagascar',
    description: 'IEHK KitsKit PED-SAMCholera kits and Tents',
    destination: 'Madagascar',
    kenyaAirways: 74431.0,
    kuehneNagel: 50943,
    scanGlobal: 41185,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 74431,
    weight: 14250.5,
    volume: 54.18,
    awardedTo: 'Scan Global',
    arrivalDate: '14-May-24',
    shippingMode: 'Air'
  },
  {
    id: 22,
    reference: 'SR_24-035_NBO hub_Comoros ',
    description: 'Cholera kitsORSTentsKIT TRAUMA (IFAK) and Visibility Items',
    destination: 'Comoros',
    kenyaAirways: 25770.0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 25770,
    weight: 9618.95,
    volume: 46.33,
    awardedTo: 'Freight In Time',
    arrivalDate: '05-Aug-24',
    shippingMode: 'Air'
  },
  {
    id: 23,
    reference: 'SR_24-033_NBO hub_Burundi',
    description: 'Tents',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 3948,
    scanGlobal: 5496,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 4933,
    weight: 1856.0,
    volume: 13.1,
    awardedTo: 'Freight In Time',
    arrivalDate: '30-May-24',
    shippingMode: 'Air'
  },
  {
    id: 24,
    reference: 'SR_24-038_NBO hub_Guinea Conakry',
    description: 'Kits and PPEs',
    destination: 'Guinea',
    kenyaAirways: 0,
    kuehneNagel: 2383,
    scanGlobal: 9588,
    dhlExpress: 3887,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 2238,
    weight: 341.0,
    volume: 1.33,
    awardedTo: 'Freight In Time',
    arrivalDate: '31-May-24',
    shippingMode: 'Air'
  },
  {
    id: 25,
    reference: 'SR_24-043_NBO hub_Benin',
    description: 'RDT Covid-19 Kits',
    destination: 'Benin',
    kenyaAirways: 0,
    kuehneNagel: 518,
    scanGlobal: 0,
    dhlExpress: 540,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 33.0,
    volume: 0.22,
    awardedTo: 'DHL Express',
    arrivalDate: '06-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 26,
    reference: 'SR_24-041_NBO hub_Zimbabwe',
    description: 'Kit Cholera Hardware and Tents',
    destination: 'Zimbabwe',
    kenyaAirways: 0,
    kuehneNagel: 8505,
    scanGlobal: 7445,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 12570,
    siginon: 0,
    freightInTime: 9742,
    weight: 6640.0,
    volume: 31.51,
    awardedTo: 'AGL',
    arrivalDate: '25-Jul-24',
    shippingMode: 'Sea'
  },
  {
    id: 27,
    reference: 'SR_24-047_NBO hub_Burundi',
    description: 'Tents',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 5478,
    scanGlobal: 4411,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 4246,
    siginon: 0,
    freightInTime: 4117,
    weight: 1604.0,
    volume: 6.68,
    awardedTo: 'Freight In Time',
    arrivalDate: '07-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 28,
    reference: 'SR_24-049_NBO hub_Zimbabwe',
    description: 'ORSINFUSION SET AND MEDICINES',
    destination: 'Zimbabwe',
    kenyaAirways: 0,
    kuehneNagel: 10446,
    scanGlobal: 10285,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 9233,
    weight: 3417.0,
    volume: 8.69,
    awardedTo: 'Freight In Time',
    arrivalDate: '15-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 29,
    reference: 'SR_24-050_NBO hub_Chad',
    description: 'RDT Covid 19 Kits',
    destination: 'Chad',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 3703,
    dhlExpress: 4739,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 3815,
    weight: 412.0,
    volume: 2.64,
    awardedTo: 'Scan Global',
    arrivalDate: '',
    shippingMode: 'Air'
  },
  {
    id: 30,
    reference: 'SR_24-059_NBI hub_GUINEA BISSAU',
    description: 'RDT Covid 19 Kits',
    destination: 'Guinea Bissau',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 942,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 88.0,
    volume: 0.58,
    awardedTo: 'DHL Express',
    arrivalDate: '30-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 31,
    reference: 'SR_24-060_NBO hub_Chad',
    description: 'TESK KITS',
    destination: 'Chad',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 11706,
    weight: 2663.75,
    volume: 9.61,
    awardedTo: 'Freight In Time',
    arrivalDate: '25-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 32,
    reference: 'SR_24-053_NBO hub_Chad',
    description: 'Kit cholera laboratory',
    destination: 'Chad',
    kenyaAirways: 0,
    kuehneNagel: 750,
    scanGlobal: 744,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 35.27,
    volume: 0.3,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '27-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 33,
    reference: 'SR_24-054_NBO hub_Togo',
    description: 'TESK KIT',
    destination: 'Togo',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 1775,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 13.0,
    volume: 0.13,
    awardedTo: 'DHL Express',
    arrivalDate: '31-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 34,
    reference: 'SR_24-051_NBO hub_Madagascar',
    description: 'IEHKTESK Kits and assorted Items',
    destination: 'Madagascar',
    kenyaAirways: 4470.0,
    kuehneNagel: 4470,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 3575,
    freightInTime: 1230,
    weight: 7.47,
    volume: 0.0,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '08-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 35,
    reference: 'SR_24-061_NBO hub_DR Congo',
    description: 'Cold chain Items and Goggles',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 3425,
    scanGlobal: 3990,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 4438,
    weight: 267.24,
    volume: 6.01,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '08-Aug-24',
    shippingMode: 'Air'
  },
  {
    id: 36,
    reference: 'SR_24-048_NBO hub_Ethiopia',
    description: 'Cholera kitsORS and Ringer Lactate',
    destination: 'Ethiopia',
    kenyaAirways: 0,
    kuehneNagel: 98758,
    scanGlobal: 140909,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 105531,
    weight: 48092.0,
    volume: 134.06,
    awardedTo: 'Freight In Time',
    arrivalDate: '15-Aug-24',
    shippingMode: 'Air'
  },
  {
    id: 37,
    reference: 'SR_24-065_NBO hub_Cote d\'lvoire',
    description: 'PPEs',
    destination: "Cote d'Ivoire",
    kenyaAirways: 0,
    kuehneNagel: 762,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 897,
    weight: 32.0,
    volume: 0.27,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '24-Aug-24',
    shippingMode: 'Air'
  },
  {
    id: 38,
    reference: 'SR_24-064_NBO hub_Central Africa Republic',
    description: 'PPEs',
    destination: 'Central Africa Republic',
    kenyaAirways: 0,
    kuehneNagel: 8345,
    scanGlobal: 7997,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 1666.0,
    volume: 6.41,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '27-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 39,
    reference: 'SR_24-068_NBO hub_Comoros',
    description: 'Cholera Laboratory and Investigation kits',
    destination: 'Comoros',
    kenyaAirways: 0,
    kuehneNagel: 966,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 1227,
    weight: 56.22,
    volume: 0.46,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '09-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 40,
    reference: 'SR_24-070_NBO hub_Togo',
    description: 'OXYGEN ANALYSER ',
    destination: 'Togo',
    kenyaAirways: 0,
    kuehneNagel: 563,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 682,
    weight: 8.66,
    volume: 0.07,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '16-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 41,
    reference: 'SR_24-072_NBO hub_Burundi',
    description: 'FREEZER',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 2723,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 2028,
    weight: 664.0,
    volume: 1.82,
    awardedTo: 'Freight In Time',
    arrivalDate: '13-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 42,
    reference: 'SR_24-071_NBO hub_DR Congo',
    description: 'ORSRinger lactate and PPEs',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 65393,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 62010,
    weight: 14500.0,
    volume: 75.0,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '09-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 43,
    reference: 'SR_24-074_NBO hub_Sudan',
    description: 'Cholera Laboratory and RDT kits',
    destination: 'Sudan',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 33.9,
    volume: 0.22,
    awardedTo: 'UNHAS ',
    arrivalDate: '19-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 44,
    reference: 'SR_24-081_NBO hub_Burundi',
    description: 'MPOX supplies ',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 29.0,
    volume: 0.28,
    awardedTo: 'Hand carried',
    arrivalDate: '25-Sept-24',
    shippingMode: 'Air'
  },
  {
    id: 45,
    reference: 'SR_24-088_NBO hub_Rwanda',
    description: 'PPEs',
    destination: 'Rwanda ',
    kenyaAirways: 0,
    kuehneNagel: 2139,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 3300,
    weight: 664.0,
    volume: 7.53,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '10-Jan-24',
    shippingMode: 'Air'
  },
  {
    id: 46,
    reference: 'SR_24-086_NBO hub_Comoros',
    description: 'Tents and Cholera kits',
    destination: 'Comoros',
    kenyaAirways: 0,
    kuehneNagel: 29032,
    scanGlobal: 26627,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 26107,
    weight: 10202.0,
    volume: 44.13,
    awardedTo: 'Freight in time',
    arrivalDate: '10-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 47,
    reference: 'SR_24-089_NBO hub_Uganda',
    description: 'Vests',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 59,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 2.4,
    volume: 0.0,
    awardedTo: 'DHL Express',
    arrivalDate: '10-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 48,
    reference: 'SR_24-082_NBO hub_Burundi',
    description: 'Ringer lactate ORS and PPEs',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 1720,
    scanGlobal: 2951,
    dhlExpress: 4377,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 2494,
    weight: 722.34,
    volume: 3.28,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '10-May-24',
    shippingMode: 'Air'
  },
  {
    id: 49,
    reference: 'SR_24-093_NBO hub_Rwanda',
    description: 'PPEs and Antifog',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 26518,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 22794,
    weight: 7445.0,
    volume: 45.65,
    awardedTo: 'Freight In time',
    arrivalDate: '10-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 50,
    reference: 'SR_24-094_NBO hub_Rwanda',
    description: 'Thermometers Piccolo and Glove Box',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 180.0,
    volume: 1.52,
    awardedTo: 'Freight In time',
    arrivalDate: '10-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 51,
    reference: 'SR_24-095_NBO hub_Rwanda',
    description: 'Marburg',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 1240,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 1576,
    weight: 369.0,
    volume: 1.72,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '16-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 52,
    reference: 'SR_24-097_NBO hub_Burundi',
    description: 'Tents',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 2297,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 2541,
    weight: 1051.0,
    volume: 4.33,
    awardedTo: 'Freight In Time',
    arrivalDate: '26-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 53,
    reference: 'SR_24-098_NBO hub_Rwanda',
    description: 'Viral RNA kits',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 286,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 811,
    weight: 22.54,
    volume: 0.21,
    awardedTo: 'Freight in Time',
    arrivalDate: '24-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 54,
    reference: 'SR_24-099_NBO hub_Burundi',
    description: 'Fuel Dispenser',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 1177,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 1619,
    weight: 283.0,
    volume: 0.99,
    awardedTo: 'Freight In Time',
    arrivalDate: '11-Jan-24',
    shippingMode: 'Air'
  },
  {
    id: 55,
    reference: 'SR_24-100_NBO hub_Uganda',
    description: 'DEFIBRILLATORS',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 354,
    scanGlobal: 0,
    dhlExpress: 822,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 654,
    weight: 51.18,
    volume: 0.46,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '24-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 56,
    reference: 'SR_24-101_NBO Hub_Rwanda',
    description: 'Mpox supplies ',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 454,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 57.16,
    volume: 0.32,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '26-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 57,
    reference: 'SR_24-102_NBO hub_Uganda',
    description: 'Mpox supplies ',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 403,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 57.16,
    volume: 0.32,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '26-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 58,
    reference: 'SR_24-103_NBO Hub_Burundi',
    description: 'Mpox supplies ',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 395,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 52.9,
    volume: 0.3,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '26-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 59,
    reference: 'SR_24-104_NBO hub_Malawi',
    description: 'Mpox supplies ',
    destination: 'Malawi',
    kenyaAirways: 0,
    kuehneNagel: 373,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 20.62,
    volume: 0.14,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '26-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 60,
    reference: 'SR_24-105_NBO hub_Rwanda',
    description: 'Vests',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 340,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 583,
    weight: 27.0,
    volume: 0.14,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '29-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 61,
    reference: 'SR_24-106_NBO hub_Rwanda',
    description: 'Feezer Aucma',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 729,
    scanGlobal: 971,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 865,
    weight: 92.0,
    volume: 1.01,
    awardedTo: 'Freight in Time',
    arrivalDate: '11-Feb-24',
    shippingMode: 'Air'
  },
  {
    id: 62,
    reference: 'SR_24-109_NBO hub_Comoros',
    description: 'Mpox supplies',
    destination: 'Comoros',
    kenyaAirways: 0,
    kuehneNagel: 356,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 10.92,
    volume: 0.08,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Jul-24',
    shippingMode: 'Air'
  },
  {
    id: 63,
    reference: 'SR_24-110_NBO hub_Madagascar',
    description: 'Mpox supplies',
    destination: 'Madagascar',
    kenyaAirways: 0,
    kuehneNagel: 396,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 20.62,
    volume: 0.14,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Jun-24',
    shippingMode: 'Air'
  },
  {
    id: 64,
    reference: 'SR_24-112_NBO hub_Benin',
    description: 'Mpox supplies',
    destination: 'Benin',
    kenyaAirways: 0,
    kuehneNagel: 492,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 19.36,
    volume: 3.21,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 65,
    reference: 'SR_24-115_NBO hub_Ghana',
    description: 'Mpox supplies',
    destination: 'Ghana',
    kenyaAirways: 0,
    kuehneNagel: 541,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 48.0,
    volume: 0.4,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '13-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 66,
    reference: 'SR_24-114_NBO hub_DR Congo',
    description: 'Glove examination',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 4328,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 899.84,
    volume: 4.1,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Oct-24',
    shippingMode: 'Air'
  },
  {
    id: 67,
    reference: 'SR_24-116_NBO hub_Rwanda',
    description: 'Extraction kits ',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 458,
    scanGlobal: 395,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 633,
    weight: 14.89,
    volume: 0.21,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 68,
    reference: 'SR_24-117_NBO hub_DR Congo',
    description: 'Mpox',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 429,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 6.03,
    volume: 0.03,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '19-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 69,
    reference: 'SR_24-120_NBO hub_ Rwanda',
    description: 'Ringers Lactate',
    destination: 'Rwanda',
    kenyaAirways: 0,
    kuehneNagel: 6589,
    scanGlobal: 5592,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 6318,
    weight: 2330.0,
    volume: 5.65,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '19-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 70,
    reference: 'SR_24-119_NBO Hub_Nigeria',
    description: 'Cold Chain Equipment',
    destination: 'Nigeria',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 455,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 10.0,
    volume: 0.1,
    awardedTo: 'DHL Express',
    arrivalDate: '25-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 71,
    reference: 'SR_24-092_NBO hub_Ethiopia ',
    description: 'CholeraIEHKPEDSAM and TESK kits',
    destination: 'Ethiopia',
    kenyaAirways: 0,
    kuehneNagel: 25898,
    scanGlobal: 27461,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 10209.0,
    volume: 28.8,
    awardedTo: 'Scan Global',
    arrivalDate: '12-Mar-24',
    shippingMode: 'Air'
  },
  {
    id: 72,
    reference: 'SR_24-123_NBO hub_DR Congo',
    description: 'IEHK Kits',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 6253,
    scanGlobal: 7478,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 6787,
    weight: 1865.0,
    volume: 10.16,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '22-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 73,
    reference: 'SR_24-134_NBO hub_Uganda',
    description: 'Mpox Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 336,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 12.0,
    volume: 0.1,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '22-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 74,
    reference: 'SR_24-135_NBO hub_Eritrea',
    description: 'Cholera RDT',
    destination: 'Eritrea',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 0.0,
    volume: 0.0,
    awardedTo: 'Hand Carried',
    arrivalDate: '',
    shippingMode: 'Air'
  },
  {
    id: 75,
    reference: 'SR_24-136_NBO hub_Burundi',
    description: 'Ampilicilin',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 167,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 12.0,
    volume: 0.02,
    awardedTo: 'DHL Express',
    arrivalDate: '29-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 76,
    reference: 'SR_24-137_NBO hub_Malawi',
    description: 'TESK Kits',
    destination: 'Malawi',
    kenyaAirways: 0,
    kuehneNagel: 13670,
    scanGlobal: 13050,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 8250,
    freightInTime: 0,
    weight: 8646.0,
    volume: 35.6,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '31-Dec-24',
    shippingMode: 'Road'
  },
  {
    id: 77,
    reference: 'SR_24-144_NBO hub_Madagascar',
    description: 'Kits and Wash items',
    destination: 'Madagascar',
    kenyaAirways: 0,
    kuehneNagel: 13560,
    scanGlobal: 11104,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 4754.0,
    volume: 22.5,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '29-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 78,
    reference: 'SR_24-146_NBO hub_Zimbabwe',
    description: 'Mpox supplies',
    destination: 'Zimbabwe',
    kenyaAirways: 0,
    kuehneNagel: 367,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 18.42,
    volume: 0.2,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '12-Nov-24',
    shippingMode: 'Air'
  },
  {
    id: 79,
    reference: 'SR_24-118A_NBO hub_South Sudan',
    description: 'Cholera Investigation and Bed',
    destination: 'South Sudan',
    kenyaAirways: 0,
    kuehneNagel: 4401,
    scanGlobal: 3911,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 4689,
    weight: 2864.5,
    volume: 10.6,
    awardedTo: 'Scan Global',
    arrivalDate: '19-Dec-24',
    shippingMode: 'Road'
  },
  {
    id: 80,
    reference: 'SR_24-150_NBO hub_Zambia',
    description: 'Cholera Lab Kits',
    destination: 'Zambia',
    kenyaAirways: 0,
    kuehneNagel: 412,
    scanGlobal: 723,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 41.32,
    volume: 0.45,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '08-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 81,
    reference: 'SR_24-151_NBO hub_Comoros',
    description: 'Cholera and Dengue RDTs',
    destination: 'Comoros',
    kenyaAirways: 0,
    kuehneNagel: 678,
    scanGlobal: 877,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 149.22,
    volume: 0.54,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '24-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 82,
    reference: 'SR_24-126_NBO hub_Eswatini',
    description: 'ISOTHERMAL BOX',
    destination: 'Eswatini',
    kenyaAirways: 0,
    kuehneNagel: 5930,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 4019,
    weight: 316.0,
    volume: 5.85,
    awardedTo: 'Freight in Time',
    arrivalDate: '27-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 83,
    reference: 'SR_24-153_NBO hub_Burundi',
    description: 'Dextrose',
    destination: 'Burundi',
    kenyaAirways: 0,
    kuehneNagel: 1218,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 533.0,
    volume: 2.09,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '31-Dec-24',
    shippingMode: 'Air'
  },
  {
    id: 84,
    reference: 'SR_24-154_NBO hub_Malawi',
    description: 'Mpox supplies and freezer',
    destination: 'Malawi',
    kenyaAirways: 0,
    kuehneNagel: 1517,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 369.0,
    volume: 1.89,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '14-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 85,
    reference: 'SR_24-118B_NBO hub_South Sudan',
    description: 'Cholera Kits and Tents',
    destination: 'South Sudan',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 8600,
    weight: 11097.0,
    volume: 49.93,
    awardedTo: 'Freight in Time',
    arrivalDate: '12-Jan-25',
    shippingMode: 'Road'
  },
  {
    id: 86,
    reference: 'SR_24-133_NBO hub_South_Sudan',
    description: 'Filovirus Kits',
    destination: 'South Sudan',
    kenyaAirways: 0,
    kuehneNagel: 366,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 895,
    weight: 10.36,
    volume: 0.04,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '15-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 87,
    reference: 'SR_25-008_NBO hub_DR Congo',
    description: 'PPEs',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 7360,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 9656,
    weight: 2203.0,
    volume: 16.04,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '10-Mar-25',
    shippingMode: 'Air'
  },
  {
    id: 88,
    reference: 'SR_25-010_ NBO hub_Tanzania',
    description: 'VHF Kits',
    destination: 'Tanzania',
    kenyaAirways: 0,
    kuehneNagel: 2783,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 1444.0,
    volume: 16.5,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '07-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 89,
    reference: 'SR_25-013_ NBO hub_Tanzania',
    description: 'Lab PPEs',
    destination: 'Tanzania',
    kenyaAirways: 0,
    kuehneNagel: 1099,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 486.0,
    volume: 2.5,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '28-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 90,
    reference: 'SR_25-001_NBO hub_Ethiopia',
    description: 'Malaria Kits',
    destination: 'Ethiopia',
    kenyaAirways: 0,
    kuehneNagel: 678,
    scanGlobal: 877,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 805.0,
    volume: 7.7,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '31-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 91,
    reference: 'SR_25-014_NBO hub_Tanzania',
    description: 'VHF Kits',
    destination: 'Tanzania',
    kenyaAirways: 0,
    kuehneNagel: 1588,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 758.0,
    volume: 3.33,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '29-Jan-25',
    shippingMode: 'Air'
  },
  {
    id: 92,
    reference: 'SR_25-019_NBO hub_Uganda ',
    description: 'EVD Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 2204,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 2204,
    freightInTime: 0,
    weight: 1422.96,
    volume: 16.48,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '02-Mar-25',
    shippingMode: 'Air'
  },
  {
    id: 93,
    reference: 'SR_25-020_NBO hub_Uganda',
    description: 'EVD Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 2204,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 2204,
    freightInTime: 0,
    weight: 1472.26,
    volume: 16.97,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '04-Mar-25',
    shippingMode: 'Air'
  },
  {
    id: 94,
    reference: 'SR_25-021_NBO hub_Uganda',
    description: 'EVD Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 2204,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 2204,
    freightInTime: 0,
    weight: 1436.58,
    volume: 16.58,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '05-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 95,
    reference: 'SR_25-022_NBO hub_Uganda',
    description: 'EVD Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 2204,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 2204,
    freightInTime: 0,
    weight: 1411.78,
    volume: 16.57,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '06-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 96,
    reference: 'SR_25-023_NBO hub_Uganda',
    description: 'EVD Kits',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 2204,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 2204,
    freightInTime: 0,
    weight: 1411.78,
    volume: 16.57,
    awardedTo: 'Siginon Logistics',
    arrivalDate: '06-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 97,
    reference: 'SR_25-018_NBO hub_Sierra Leone',
    description: 'PPEs and pharmaceuticals',
    destination: 'Sierra Leone',
    kenyaAirways: 0,
    kuehneNagel: 7350,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 7936,
    weight: 1965.54,
    volume: 9.81,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '18-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 98,
    reference: 'SR_25-017_NBO hub_DR Congo',
    description: 'PPEs',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 8552,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 10648,
    weight: 2566.08,
    volume: 17.67,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '14-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 99,
    reference: 'SR_25-015_NBO hub_Sao Tome',
    description: 'PPEs',
    destination: 'Sao Tome',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 307,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 11.72,
    volume: 0.12,
    awardedTo: 'DHl Express',
    arrivalDate: '25-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 100,
    reference: 'SR_25-026_NBO hub_Uganda',
    description: 'Biosafety cabinets ',
    destination: 'Uganda',
    kenyaAirways: 0,
    kuehneNagel: 590,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 964,
    weight: 191.28,
    volume: 1.29,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '11-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 101,
    reference: 'SR_25-025_NBO hub_Eritrea',
    description: 'Lab supplies',
    destination: 'Eritrea',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 21.76,
    volume: 0.21,
    awardedTo: 'Hand carried',
    arrivalDate: '13-Feb-25',
    shippingMode: 'Air'
  },
  {
    id: 102,
    reference: 'SR_25-024_NBO hub_DR Congo',
    description: 'TESKIEHK Kits and TENTS ?Ã¿ PPES',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 8400,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 10000,
    freightInTime: 0,
    weight: 12700.0,
    volume: 63.68,
    awardedTo: 'Siginon based on contractual history and performance',
    arrivalDate: '26-Feb-25',
    shippingMode: 'Road'
  },
  {
    id: 103,
    reference: 'SR_25-032_NBO hub_Sao Tome',
    description: 'Remel swabs',
    destination: 'Sao Tome',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 270,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 20.0,
    volume: 0.23,
    awardedTo: 'DHL Express',
    arrivalDate: '12-Mar-25',
    shippingMode: 'Air'
  },
  {
    id: 104,
    reference: 'SR_25-031_NBO hub_Guinea',
    description: 'Remel swabs',
    destination: 'Guinea',
    kenyaAirways: 0,
    kuehneNagel: 0,
    scanGlobal: 0,
    dhlExpress: 270,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 0,
    weight: 20.0,
    volume: 0.23,
    awardedTo: 'DHL Express',
    arrivalDate: '06-Mar-25',
    shippingMode: 'Air'
  },
  {
    id: 105,
    reference: 'SR_25-033_NBO hub_DR Congo',
    description: 'PPEs and Lab Supplies ',
    destination: 'DR Congo',
    kenyaAirways: 0,
    kuehneNagel: 798,
    scanGlobal: 0,
    dhlExpress: 0,
    dhlGlobal: 0,
    bwosi: 0,
    agl: 0,
    siginon: 0,
    freightInTime: 990,
    weight: 192.7,
    volume: 0.94,
    awardedTo: 'Kuehne Nagel',
    arrivalDate: '06-Mar-25',
    shippingMode: 'Air'
  }
  
];

// Process the raw freight data into analytics
export function processFreightData(data: FreightRow[]): FreightAnalytics {
  const analytics: FreightAnalytics = {
    totalShipments: data.length,
    totalWeight: 0,
    totalVolume: 0,
    ratePerKg: {},
    ratePerCountry: {},
    shipmentsPerForwarder: {
      'Kenya Airways': 0,
      'Kuehne and Nagel': 0,
      'Scan Global': 0,
      'DHL Express': 0,
      'DHL Global': 0,
      'Bwosi': 0,
      'AGL': 0,
      'Siginon': 0,
      'Freight In Time': 0,
    },
    favorableFreight: [],
    shipmentsByCountry: {},
  };

  // Forwarder rate sums for average calculation
  const rateSums: { [key: string]: { total: number, count: number } } = {
    'Kenya Airways': { total: 0, count: 0 },
    'Kuehne and Nagel': { total: 0, count: 0 },
    'Scan Global': { total: 0, count: 0 },
    'DHL Express': { total: 0, count: 0 },
    'DHL Global': { total: 0, count: 0 },
    'Bwosi': { total: 0, count: 0 },
    'AGL': { total: 0, count: 0 },
    'Siginon': { total: 0, count: 0 },
    'Freight In Time': { total: 0, count: 0 },
  };

  // Country forwarder rate sums
  const countryRates: { [country: string]: { [forwarder: string]: { total: number, count: number } } } = {};

  // Process each shipment
  data.forEach(shipment => {
    // Add to totals
    analytics.totalWeight += shipment.weight;
    analytics.totalVolume += shipment.volume;

    // Count by awarded forwarder
    if (shipment.awardedTo.includes('Kenya Airways')) analytics.shipmentsPerForwarder['Kenya Airways']++;
    if (shipment.awardedTo.includes('Kuehne Nagel') || shipment.awardedTo.includes('Kuehne and Nagel')) analytics.shipmentsPerForwarder['Kuehne and Nagel']++;
    if (shipment.awardedTo.includes('Scan Global')) analytics.shipmentsPerForwarder['Scan Global']++;
    if (shipment.awardedTo.includes('DHL Express')) analytics.shipmentsPerForwarder['DHL Express']++;
    if (shipment.awardedTo.includes('DHL Global')) analytics.shipmentsPerForwarder['DHL Global']++;
    if (shipment.awardedTo.includes('Bwosi')) analytics.shipmentsPerForwarder['Bwosi']++;
    if (shipment.awardedTo.includes('AGL')) analytics.shipmentsPerForwarder['AGL']++;
    if (shipment.awardedTo.includes('Siginon')) analytics.shipmentsPerForwarder['Siginon']++;
    if (shipment.awardedTo.includes('Freight In Time') || shipment.awardedTo.includes('Freight in Time')) analytics.shipmentsPerForwarder['Freight In Time']++;

    // Count shipments by country
    if (!analytics.shipmentsByCountry[shipment.destination]) {
      analytics.shipmentsByCountry[shipment.destination] = 0;
    }
    analytics.shipmentsByCountry[shipment.destination]++;

    // Calculate rates per kg for different forwarders
    if (shipment.weight > 0) {
      // Process each forwarder's rate
      if (shipment.kenyaAirways > 0) {
        const rate = shipment.kenyaAirways / shipment.weight;
        rateSums['Kenya Airways'].total += rate;
        rateSums['Kenya Airways'].count++;

        // Add to country-specific rates
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['Kenya Airways']) {
          countryRates[shipment.destination]['Kenya Airways'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['Kenya Airways'].total += rate;
        countryRates[shipment.destination]['Kenya Airways'].count++;
      }

      // Apply the same logic for other forwarders
      if (shipment.kuehneNagel > 0) {
        const rate = shipment.kuehneNagel / shipment.weight;
        rateSums['Kuehne and Nagel'].total += rate;
        rateSums['Kuehne and Nagel'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['Kuehne and Nagel']) {
          countryRates[shipment.destination]['Kuehne and Nagel'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['Kuehne and Nagel'].total += rate;
        countryRates[shipment.destination]['Kuehne and Nagel'].count++;
      }

      // Scan Global
      if (shipment.scanGlobal > 0) {
        const rate = shipment.scanGlobal / shipment.weight;
        rateSums['Scan Global'].total += rate;
        rateSums['Scan Global'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['Scan Global']) {
          countryRates[shipment.destination]['Scan Global'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['Scan Global'].total += rate;
        countryRates[shipment.destination]['Scan Global'].count++;
      }

      // DHL Express
      if (shipment.dhlExpress > 0) {
        const rate = shipment.dhlExpress / shipment.weight;
        rateSums['DHL Express'].total += rate;
        rateSums['DHL Express'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['DHL Express']) {
          countryRates[shipment.destination]['DHL Express'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['DHL Express'].total += rate;
        countryRates[shipment.destination]['DHL Express'].count++;
      }

      // Freight In Time
      if (shipment.freightInTime > 0) {
        const rate = shipment.freightInTime / shipment.weight;
        rateSums['Freight In Time'].total += rate;
        rateSums['Freight In Time'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['Freight In Time']) {
          countryRates[shipment.destination]['Freight In Time'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['Freight In Time'].total += rate;
        countryRates[shipment.destination]['Freight In Time'].count++;
      }

      // Other forwarders follow the same pattern...
      // AGL
      if (shipment.agl > 0) {
        const rate = shipment.agl / shipment.weight;
        rateSums['AGL'].total += rate;
        rateSums['AGL'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['AGL']) {
          countryRates[shipment.destination]['AGL'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['AGL'].total += rate;
        countryRates[shipment.destination]['AGL'].count++;
      }

      // Siginon
      if (shipment.siginon > 0) {
        const rate = shipment.siginon / shipment.weight;
        rateSums['Siginon'].total += rate;
        rateSums['Siginon'].count++;
        
        if (!countryRates[shipment.destination]) {
          countryRates[shipment.destination] = {};
        }
        if (!countryRates[shipment.destination]['Siginon']) {
          countryRates[shipment.destination]['Siginon'] = { total: 0, count: 0 };
        }
        countryRates[shipment.destination]['Siginon'].total += rate;
        countryRates[shipment.destination]['Siginon'].count++;
      }
    }
  });

  // Calculate average rate per kg for each forwarder
  for (const [forwarder, sums] of Object.entries(rateSums)) {
    if (sums.count > 0) {
      analytics.ratePerKg[forwarder] = parseFloat((sums.total / sums.count).toFixed(2));
    } else {
      analytics.ratePerKg[forwarder] = 0;
    }
  }

  // Calculate average rate per country for each forwarder
  analytics.ratePerCountry = {};
  for (const [country, forwarders] of Object.entries(countryRates)) {
    analytics.ratePerCountry[country] = {};
    for (const [forwarder, sums] of Object.entries(forwarders)) {
      if (sums.count > 0) {
        analytics.ratePerCountry[country][forwarder] = parseFloat((sums.total / sums.count).toFixed(2));
      }
    }
  }

  // Calculate favorable freight based on price and availability
  // Lower score is better (normalized price * 0.7 + normalized availability * 0.3)
  const forwarders = Object.keys(analytics.shipmentsPerForwarder);
  const availabilityScores: { [key: string]: number } = {};
  const priceScores: { [key: string]: number } = {};
  
  // Get max values for normalization
  const maxShipments = Math.max(...Object.values(analytics.shipmentsPerForwarder));
  const maxRate = Math.max(...Object.values(analytics.ratePerKg).filter(rate => rate > 0));
  
  // Calculate normalized scores
  forwarders.forEach(forwarder => {
    // Availability score (higher is better)
    const availability = analytics.shipmentsPerForwarder[forwarder] / maxShipments;
    availabilityScores[forwarder] = availability;
    
    // Price score (lower is better)
    const price = analytics.ratePerKg[forwarder] / maxRate;
    priceScores[forwarder] = analytics.ratePerKg[forwarder] > 0 ? price : 1; // If no price data, assume worst
  });
  
  // Calculate final scores (lower is better)
  forwarders.forEach(forwarder => {
    if (analytics.shipmentsPerForwarder[forwarder] > 0) {
      analytics.favorableFreight.push({
        name: forwarder,
        score: (priceScores[forwarder] * 0.7) - (availabilityScores[forwarder] * 0.3),
        averagePrice: analytics.ratePerKg[forwarder],
        availability: analytics.shipmentsPerForwarder[forwarder]
      });
    }
  });
  
  // Sort by score (lower is better)
  analytics.favorableFreight.sort((a, b) => a.score - b.score);
  
  return analytics;
}

export const freightAnalytics = processFreightData(freightData);
