# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, best_forwarder: str=None, route_score: float=None, rules_fired: List[str]=None, explanation: List[str]=None, route_overlay_url: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param best_forwarder: The best_forwarder of this InlineResponse200.  # noqa: E501
        :type best_forwarder: str
        :param route_score: The route_score of this InlineResponse200.  # noqa: E501
        :type route_score: float
        :param rules_fired: The rules_fired of this InlineResponse200.  # noqa: E501
        :type rules_fired: List[str]
        :param explanation: The explanation of this InlineResponse200.  # noqa: E501
        :type explanation: List[str]
        :param route_overlay_url: The route_overlay_url of this InlineResponse200.  # noqa: E501
        :type route_overlay_url: str
        """
        self.swagger_types = {
            'best_forwarder': str,
            'route_score': float,
            'rules_fired': List[str],
            'explanation': List[str],
            'route_overlay_url': str
        }

        self.attribute_map = {
            'best_forwarder': 'best_forwarder',
            'route_score': 'route_score',
            'rules_fired': 'rules_fired',
            'explanation': 'explanation',
            'route_overlay_url': 'route_overlay_url'
        }
        self._best_forwarder = best_forwarder
        self._route_score = route_score
        self._rules_fired = rules_fired
        self._explanation = explanation
        self._route_overlay_url = route_overlay_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def best_forwarder(self) -> str:
        """Gets the best_forwarder of this InlineResponse200.


        :return: The best_forwarder of this InlineResponse200.
        :rtype: str
        """
        return self._best_forwarder

    @best_forwarder.setter
    def best_forwarder(self, best_forwarder: str):
        """Sets the best_forwarder of this InlineResponse200.


        :param best_forwarder: The best_forwarder of this InlineResponse200.
        :type best_forwarder: str
        """

        self._best_forwarder = best_forwarder

    @property
    def route_score(self) -> float:
        """Gets the route_score of this InlineResponse200.


        :return: The route_score of this InlineResponse200.
        :rtype: float
        """
        return self._route_score

    @route_score.setter
    def route_score(self, route_score: float):
        """Sets the route_score of this InlineResponse200.


        :param route_score: The route_score of this InlineResponse200.
        :type route_score: float
        """

        self._route_score = route_score

    @property
    def rules_fired(self) -> List[str]:
        """Gets the rules_fired of this InlineResponse200.


        :return: The rules_fired of this InlineResponse200.
        :rtype: List[str]
        """
        return self._rules_fired

    @rules_fired.setter
    def rules_fired(self, rules_fired: List[str]):
        """Sets the rules_fired of this InlineResponse200.


        :param rules_fired: The rules_fired of this InlineResponse200.
        :type rules_fired: List[str]
        """

        self._rules_fired = rules_fired

    @property
    def explanation(self) -> List[str]:
        """Gets the explanation of this InlineResponse200.


        :return: The explanation of this InlineResponse200.
        :rtype: List[str]
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation: List[str]):
        """Sets the explanation of this InlineResponse200.


        :param explanation: The explanation of this InlineResponse200.
        :type explanation: List[str]
        """

        self._explanation = explanation

    @property
    def route_overlay_url(self) -> str:
        """Gets the route_overlay_url of this InlineResponse200.


        :return: The route_overlay_url of this InlineResponse200.
        :rtype: str
        """
        return self._route_overlay_url

    @route_overlay_url.setter
    def route_overlay_url(self, route_overlay_url: str):
        """Sets the route_overlay_url of this InlineResponse200.


        :param route_overlay_url: The route_overlay_url of this InlineResponse200.
        :type route_overlay_url: str
        """

        self._route_overlay_url = route_overlay_url
