# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.analyze_output import AnalyzeOutput  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, historical_decision: AnalyzeOutput=None, cognitive_log: List[str]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param historical_decision: The historical_decision of this InlineResponse2002.  # noqa: E501
        :type historical_decision: AnalyzeOutput
        :param cognitive_log: The cognitive_log of this InlineResponse2002.  # noqa: E501
        :type cognitive_log: List[str]
        """
        self.swagger_types = {
            'historical_decision': AnalyzeOutput,
            'cognitive_log': List[str]
        }

        self.attribute_map = {
            'historical_decision': 'historical_decision',
            'cognitive_log': 'cognitive_log'
        }
        self._historical_decision = historical_decision
        self._cognitive_log = cognitive_log

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def historical_decision(self) -> AnalyzeOutput:
        """Gets the historical_decision of this InlineResponse2002.


        :return: The historical_decision of this InlineResponse2002.
        :rtype: AnalyzeOutput
        """
        return self._historical_decision

    @historical_decision.setter
    def historical_decision(self, historical_decision: AnalyzeOutput):
        """Sets the historical_decision of this InlineResponse2002.


        :param historical_decision: The historical_decision of this InlineResponse2002.
        :type historical_decision: AnalyzeOutput
        """

        self._historical_decision = historical_decision

    @property
    def cognitive_log(self) -> List[str]:
        """Gets the cognitive_log of this InlineResponse2002.


        :return: The cognitive_log of this InlineResponse2002.
        :rtype: List[str]
        """
        return self._cognitive_log

    @cognitive_log.setter
    def cognitive_log(self, cognitive_log: List[str]):
        """Sets the cognitive_log of this InlineResponse2002.


        :param cognitive_log: The cognitive_log of this InlineResponse2002.
        :type cognitive_log: List[str]
        """

        self._cognitive_log = cognitive_log
