# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, description: str=None, result: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param id: The id of this InlineResponse2001.  # noqa: E501
        :type id: str
        :param description: The description of this InlineResponse2001.  # noqa: E501
        :type description: str
        :param result: The result of this InlineResponse2001.  # noqa: E501
        :type result: str
        """
        self.swagger_types = {
            'id': str,
            'description': str,
            'result': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'result': 'result'
        }
        self._id = id
        self._description = description
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2001.


        :return: The id of this InlineResponse2001.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2001.


        :param id: The id of this InlineResponse2001.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this InlineResponse2001.


        :return: The description of this InlineResponse2001.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this InlineResponse2001.


        :param description: The description of this InlineResponse2001.
        :type description: str
        """

        self._description = description

    @property
    def result(self) -> str:
        """Gets the result of this InlineResponse2001.


        :return: The result of this InlineResponse2001.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result: str):
        """Sets the result of this InlineResponse2001.


        :param result: The result of this InlineResponse2001.
        :type result: str
        """
        allowed_values = ["passed", "failed"]  # noqa: E501
        if result not in allowed_values:
            raise ValueError(
                "Invalid value for `result` ({0}), must be one of {1}"
                .format(result, allowed_values)
            )

        self._result = result
